"""Bio column added

Revision ID: a701a97c6cdf
Revises: 17cf204b07e7
Create Date: 2024-10-21 23:18:25.478598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a701a97c6cdf'
down_revision = '17cf204b07e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lawyer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lawyer', schema=None) as batch_op:
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
